name: AndroidLint

on:
  pull_request:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  android-lint:
    runs-on: ubuntu-latest
    name: Android Application Lint Check-Up
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distributions: zulu
          java-version: 11
          cache: gradle
      - run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml
          continue-on-error: false
