name: LinkCheck, Test, Build and Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  lint:
    name: Running Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - run: chmod +x ./gradlew
      - run: ./gradlew lint
      - run: ./gradlew test
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml
